## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

spring:
  application:
    name: school
  datasource:
    hikari:
      autocommit: false
    url: "jdbc:postgresql://localhost:5432/postgres"
 #   url: "jdbc:postgresql://10.10.25.157:5432/postgres"
    username: postgres
    password: postgres
#    password: 23people
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: carlos
        
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /${spring.application.name}